language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.3
  - DJANGO_VERSION=1.4.1
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .
  - pip install BeautifulSoup
  - pip install django-categories
script:
  - ./run_tests.py
branches:
  only:
    - 1.0