language: python
python:
  - "2.6"
  - "2.7"
env:
  - DV=1.2.7 CV=1.1
  - DV=1.2.7 CV=1.1.1
  - DV=1.2.7 CV=1.1.2
  - DV=1.3.3 CV=1.1
  - DV=1.3.3 CV=1.1.1
  - DV=1.3.3 CV=1.1.2
  - DV=1.4.1 CV=1.1
  - DV=1.4.1 CV=1.1.1
  - DV=1.4.1 CV=1.1.2
install:
  - pip install Django==$DV
  - pip install django-categories==$CV
  - pip install -e .
  - pip install BeautifulSoup django-staticfiles south
script:
  - ./run_tests.py
branches:
  only:
    - 1.0
notifications:
  email:
    - ci@callowayproject.com